### ISSUE TITLE
Darwin support?

### ISSUE THREAD

**Issue by RaitoBezarius** [Foxboron/go-uefi#13]
Hi there, thank you for the amazing library.

Naive question from my part, but AFAIK, Darwin platforms such `x86_64-darwin` and `aarch64-darwin` could be in the scope of UEFI manipulations, right?

From what I see, I think this library depend on some `unix.XXX` variables which prevent `sbctl` for example to be built on these machines, do you think it would be a good idea to track support for Darwin in this issue or is this a non-feature for this library?

(To be completely precise, this comes from a failure on NixOS CI for `sbctl` that I maintain: https://hydra.nixos.org/build/197514784/nixlog/1 which seems to indicate that `go-uefi` cannot support this target. But this is a more general question for this ecosystem.)

**Comment by Foxboron** [comment]
This was fixed with https://github.com/Foxboron/go-uefi/commit/3068c281e4d6d5379851284cedfbaa1a7251519e but `sbctl` hasn't been rebuilt with the new patch. But the project wont work anyway.

I don't have any plans supporting darwin in either `sbctl` nor `go-uefi`.

**Comment by RaitoBezarius** [comment]
@Foxboron would you suggest me to keep the supported platforms for `sbctl` to UNIX derivatives?

**Comment by Foxboron** [comment]
I don't quite see who would implement this on Darwin and then try upstream support for it into `sbctl`. So keeping it to Linux-only makes sense.

**Comment by RaitoBezarius** [comment]
Sounds good, thank you for your time!
